### ISSUE TITLE
User permissions

### ISSUE THREAD

**Issue by davidkuehner** [diegoantognini/Back-To-School#15]
**Tasks :** 
- Code global user permissions

**Deliveries :**
- Source code for user permissions

**Comment by maeberli** [comment]
The development of [CanCan](https://github.com/ryanb/cancan) - the classic gem for handling user permissions - has stopped. So no updates for RoR will be availlable. With some workarounds it could be possible to get work CanCan with RoR, but this won't will last for long.

Alternatives are proposed in [this](http://stackoverflow.com/questions/20486316/cancan-not-fully-supported-in-rails-4) SO article.

To evaluate:
- declarative_authorization
- rolify 
- pundit

**Comment by maeberli** [comment]
After a short try of the combination of:
- Rolify (Attribe a user role to a ressource, i.e.: aeberli is admin in Forum1, Antognini is reader in Forum1, ...)
- Devise ( Authentification, includes functionality for remember, timeout, ...)

and
- Authority ( allows to manage the permission on controller, actions, ... => authorization )
  https://github.com/EppO/rolify/wiki/Using-rolify-with-Devise-and-Authority

The Combination of Devise and Authority should sufficient for B2S
