### ISSUE TITLE
Deploy example on productive server

### ISSUE THREAD

**Issue by diegoantognini** [diegoantognini/Back-To-School#2]

**Comment by maeberli** [comment]
First try to deploy the ProofOfConcept_EMail branch to the server.
1) cloned git repository
2) checked out the ProofOfConcept_EMail branch
3) Setup of the apache  virtual host file
4) created unique application key with:

``` sh
rake secret
```

5) created _./config/initializers/secret_token.rb_ file

``` ruby
BackToSchool::Application.config.secret_key_base =  'KEY_GOES_HERE'
```

6) appended the following lines to _./config/environments/production.rb_

``` ruby
  # Back-To-School modificiations
  config.action_mailer.delivery_method = :smtp
  config.action_mailer.smtp_settings = {
    address:              'smtpgw1.he-arc.ch',
  }
```

**Comment by davidkuehner** [comment]
Deploy example with capistrano, smart secret token, and proxy fix
