### ISSUE TITLE
Search functionality 

### ISSUE THREAD

**Issue by davidkuehner** [diegoantognini/Back-To-School#23]
**Tasks :** 
- Code possibility to search users and groups

**Deliveries :**
- Source code for the search page

**Comment by maeberli** [comment]
Some interesting gems and technologies found to solve the global search problem.

A "smaller" gem for easy searches: https://github.com/ankane/searchkick
An integration gem for sphinx searches(seems to be really complete and powerful): http://pat.github.io/thinking-sphinx/
