### ISSUE TITLE
Prepare presentation

### ISSUE THREAD

**Issue by diegoantognini** [diegoantognini/Back-To-School#5]

**Comment by maeberli** [comment]
**Tasks :** 
- Elaborate the content of the presentation
- Create slide design adapted to Back-To-Schoool CI
- Create the slides for the presentation
- Note slide attribution in slide notes.

**Description :**
- At the end of the project, Back-To-School will be presented in front of teacher and class. So a presentation has to be elaborated.

**Deliveries :**
- Powerpoint presentation with adapted Design, content and slide attribution.

**Comment by davidkuehner** [comment]
😂

**Comment by diegoantognini** [comment]
J'ai vu ça dans mes issues, c'était pas jolie 😉
—
Diego Antognini

**Comment by grunenwald** [comment]
ouala, c'est propre en ordre ! ;)
