### ISSUE TITLE
Incoherence in database seed

### ISSUE THREAD

**Issue by davidkuehner** [diegoantognini/Back-To-School#52]
1. Michael Muller is both in DLM and IEE (maybe it's a secial case, so why is he also in the follower ?)
2. Adian Moll isn't in the DLM but he posted in he DLM discussion
3. Maybe add the whole classes in DLM 2014 and IEE 2014

**Comment by maeberli** [comment]
I will leave Michael Muller in both promotions, but i will remove him from the following list.

**Comment by maeberli** [comment]
I will add AM to the DLM students.

**Comment by davidkuehner** [comment]
As discussed, we will remove the seed.rb from versionning system and send it with capistrano to avoid data exposure.
